# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2

updates:

  - package-ecosystem: composer
    directory: "/"
    registries: "*"
    schedule:
      interval: daily
      time: "01:10"
      timezone: "Europe/London"
    versioning-strategy: increase
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Upgraded"
      prefix-development: "Upgraded"

  # Project Workflows
  - package-ecosystem: 'github-actions'
    directory: "/"
    schedule:
      interval: 'daily'
      time: '00:55'
      timezone: 'Europe/London'
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Upgraded"
      prefix-development: "Upgraded"
